# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
    ]
