# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='session_key',
        ),
    ]
